# Generated by Django 3.1.4 on 2020-12-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=2083, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('releaseDate', models.DateTimeField()),
                ('score', models.CharField(max_length=200)),
                ('consoles', models.CharField(max_length=200)),
            ],
        ),
    ]
