# Generated by Django 3.1.4 on 2020-12-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(default='', max_length=64)),
                ('link', models.CharField(default='', max_length=64)),
                ('title', models.CharField(default='', max_length=64)),
                ('developer', models.CharField(default='', max_length=64)),
                ('releaseDate', models.DateField(default='', max_length=64)),
                ('score', models.FloatField(default=0, max_length=64)),
                ('steamReview', models.CharField(default='', max_length=64)),
                ('consoles', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
