# Generated by Django 3.1.4 on 2020-12-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20201216_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
