# Generated by Django 3.1.4 on 2020-12-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_reviews_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.CharField(max_length=200),
        ),
    ]
