# Generated by Django 3.1.4 on 2020-12-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0004_auto_20201216_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='steamReview',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='developer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.FloatField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
